import type {
  Policial,
  Impedimento,
  Viagem,
  Sobreaviso,
  AuditLog,
  Notificacao,
} from '@/types';
import { addDays, subDays, startOfToday, setHours, setMinutes } from 'date-fns';

// ============================================================
// Mock Data — Realistic Brazilian Federal Police officers
// ============================================================

const today = startOfToday();

export const MOCK_POLICIAIS: Policial[] = [
  {
    id: 'policial_demo_1',
    nome: 'Carlos Eduardo Silva',
    email: 'carlos.silva@pf.gov.br',
    cpf_matricula: '123.456.789-00',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 12,
    dias_acumulados_sobreaviso: 8,
    created_at: subDays(today, 180),
    updated_at: subDays(today, 2),
  },
  {
    id: 'policial_demo_2',
    nome: 'Ana Paula Ribeiro',
    email: 'ana.ribeiro@pf.gov.br',
    cpf_matricula: '234.567.890-11',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 9,
    dias_acumulados_sobreaviso: 14,
    created_at: subDays(today, 200),
    updated_at: subDays(today, 5),
  },
  {
    id: 'policial_demo_3',
    nome: 'Rafael Mendes Costa',
    email: 'rafael.costa@pf.gov.br',
    cpf_matricula: '345.678.901-22',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 18,
    dias_acumulados_sobreaviso: 6,
    created_at: subDays(today, 150),
    updated_at: subDays(today, 1),
  },
  {
    id: 'policial_demo_4',
    nome: 'Fernanda Oliveira Santos',
    email: 'fernanda.santos@pf.gov.br',
    cpf_matricula: '456.789.012-33',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 5,
    dias_acumulados_sobreaviso: 11,
    created_at: subDays(today, 120),
    updated_at: subDays(today, 3),
  },
  {
    id: 'policial_demo_5',
    nome: 'Lucas Tavares Pereira',
    email: 'lucas.pereira@pf.gov.br',
    cpf_matricula: '567.890.123-44',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 22,
    dias_acumulados_sobreaviso: 3,
    created_at: subDays(today, 300),
    updated_at: subDays(today, 7),
  },
  {
    id: 'policial_demo_6',
    nome: 'Mariana Almeida Rocha',
    email: 'mariana.rocha@pf.gov.br',
    cpf_matricula: '678.901.234-55',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 15,
    dias_acumulados_sobreaviso: 9,
    created_at: subDays(today, 250),
    updated_at: subDays(today, 4),
  },
  {
    id: 'policial_demo_7',
    nome: 'Pedro Henrique Lima',
    email: 'pedro.lima@pf.gov.br',
    cpf_matricula: '789.012.345-66',
    status: 'inativo',
    role: 'policial',
    pontos_acumulados_viagem: 7,
    dias_acumulados_sobreaviso: 2,
    created_at: subDays(today, 400),
    updated_at: subDays(today, 30),
  },
  {
    id: 'policial_demo_8',
    nome: 'Juliana Monteiro Dias',
    email: 'juliana.dias@pf.gov.br',
    cpf_matricula: '890.123.456-77',
    status: 'ativo',
    role: 'policial',
    pontos_acumulados_viagem: 11,
    dias_acumulados_sobreaviso: 17,
    created_at: subDays(today, 160),
    updated_at: subDays(today, 1),
  },
];

export const MOCK_VIAGENS: Viagem[] = [
  {
    id: 'viagem_001',
    destino: 'Curitiba - PR (SR/PR)',
    data_inicio: subDays(today, 10),
    data_fim: subDays(today, 7),
    nivel: 2,
    policial_designado: 'policial_demo_3',
    nome_policial: 'Rafael Mendes Costa',
    status: 'confirmado',
    pontos: 2,
    created_at: subDays(today, 15),
    updated_at: subDays(today, 7),
  },
  {
    id: 'viagem_002',
    destino: 'Salvador - BA (DPF/SSA)',
    data_inicio: subDays(today, 5),
    data_fim: subDays(today, 2),
    nivel: 1,
    policial_designado: 'policial_demo_1',
    nome_policial: 'Carlos Eduardo Silva',
    status: 'confirmado',
    pontos: 1,
    created_at: subDays(today, 8),
    updated_at: subDays(today, 2),
  },
  {
    id: 'viagem_003',
    destino: 'Manaus - AM (SR/AM)',
    data_inicio: addDays(today, 2),
    data_fim: addDays(today, 12),
    nivel: 3,
    policial_designado: 'policial_demo_4',
    nome_policial: 'Fernanda Oliveira Santos',
    status: 'pendente',
    pontos: 3,
    created_at: subDays(today, 3),
    updated_at: subDays(today, 3),
  },
  {
    id: 'viagem_004',
    destino: 'Brasília - DF (CGDI/DICOR)',
    data_inicio: addDays(today, 5),
    data_fim: addDays(today, 8),
    nivel: 2,
    policial_designado: 'policial_demo_2',
    nome_policial: 'Ana Paula Ribeiro',
    status: 'pendente',
    pontos: 2,
    created_at: subDays(today, 1),
    updated_at: subDays(today, 1),
  },
  {
    id: 'viagem_005',
    destino: 'Foz do Iguaçu - PR (DPF/FIG)',
    data_inicio: subDays(today, 20),
    data_fim: subDays(today, 10),
    nivel: 'longa_duracao',
    policial_designado: 'policial_demo_5',
    nome_policial: 'Lucas Tavares Pereira',
    status: 'confirmado',
    pontos: 3,
    created_at: subDays(today, 25),
    updated_at: subDays(today, 10),
  },
  {
    id: 'viagem_006',
    destino: 'Recife - PE (SR/PE)',
    data_inicio: addDays(today, 14),
    data_fim: addDays(today, 17),
    nivel: 1,
    policial_designado: 'policial_demo_6',
    nome_policial: 'Mariana Almeida Rocha',
    status: 'pendente',
    pontos: 1,
    created_at: today,
    updated_at: today,
  },
];

export const MOCK_SOBREAVISOS: Sobreaviso[] = [
  {
    id: 'sobreaviso_001',
    data: today,
    horario_inicio: setMinutes(setHours(today, 18), 0),
    horario_fim: setMinutes(setHours(addDays(today, 1), 6), 0),
    policial_designado: 'policial_demo_1',
    nome_policial: 'Carlos Eduardo Silva',
    status: 'confirmado',
    created_at: subDays(today, 3),
    updated_at: today,
  },
  {
    id: 'sobreaviso_002',
    data: today,
    horario_inicio: setMinutes(setHours(today, 18), 0),
    horario_fim: setMinutes(setHours(addDays(today, 1), 6), 0),
    policial_designado: 'policial_demo_2',
    nome_policial: 'Ana Paula Ribeiro',
    status: 'pendente',
    created_at: subDays(today, 2),
    updated_at: subDays(today, 2),
  },
  {
    id: 'sobreaviso_003',
    data: addDays(today, 1),
    horario_inicio: setMinutes(setHours(addDays(today, 1), 18), 0),
    horario_fim: setMinutes(setHours(addDays(today, 2), 6), 0),
    policial_designado: 'policial_demo_3',
    nome_policial: 'Rafael Mendes Costa',
    status: 'pendente',
    created_at: subDays(today, 1),
    updated_at: subDays(today, 1),
  },
  {
    id: 'sobreaviso_004',
    data: addDays(today, 2),
    horario_inicio: setMinutes(setHours(addDays(today, 2), 18), 0),
    horario_fim: setMinutes(setHours(addDays(today, 3), 6), 0),
    policial_designado: 'policial_demo_6',
    nome_policial: 'Mariana Almeida Rocha',
    status: 'pendente',
    created_at: today,
    updated_at: today,
  },
  {
    id: 'sobreaviso_005',
    data: subDays(today, 1),
    horario_inicio: setMinutes(setHours(subDays(today, 1), 18), 0),
    horario_fim: setMinutes(setHours(today, 6), 0),
    policial_designado: 'policial_demo_8',
    nome_policial: 'Juliana Monteiro Dias',
    status: 'confirmado',
    created_at: subDays(today, 4),
    updated_at: subDays(today, 1),
  },
];

export const MOCK_IMPEDIMENTOS: Impedimento[] = [
  {
    id: 'impedimento_001',
    id_policial: 'policial_demo_7',
    nome_policial: 'Pedro Henrique Lima',
    tipo: 'licenca',
    data_inicio: subDays(today, 30),
    data_fim: addDays(today, 15),
    created_at: subDays(today, 35),
  },
  {
    id: 'impedimento_002',
    id_policial: 'policial_demo_5',
    nome_policial: 'Lucas Tavares Pereira',
    tipo: 'curso',
    data_inicio: addDays(today, 20),
    data_fim: addDays(today, 35),
    created_at: subDays(today, 5),
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit_001',
    admin_id: 'admin_001',
    admin_nome: 'Delegado Marcos Vieira',
    action: 'create',
    collection: 'viagens',
    document_id: 'viagem_006',
    timestamp: new Date(today.getTime() - 1000 * 60 * 30), // 30 min ago
  },
  {
    id: 'audit_002',
    admin_id: 'admin_001',
    admin_nome: 'Delegado Marcos Vieira',
    action: 'update',
    collection: 'sobreaviso',
    document_id: 'sobreaviso_001',
    timestamp: new Date(today.getTime() - 1000 * 60 * 60 * 2), // 2h ago
  },
  {
    id: 'audit_003',
    admin_id: 'admin_002',
    admin_nome: 'Escrivã Paula Nascimento',
    action: 'update',
    collection: 'policiais',
    document_id: 'policial_demo_7',
    old_data: { status: 'ativo' },
    new_data: { status: 'inativo' },
    timestamp: new Date(today.getTime() - 1000 * 60 * 60 * 5), // 5h ago
  },
  {
    id: 'audit_004',
    admin_id: 'admin_001',
    admin_nome: 'Delegado Marcos Vieira',
    action: 'create',
    collection: 'viagens',
    document_id: 'viagem_005',
    timestamp: subDays(today, 1),
  },
  {
    id: 'audit_005',
    admin_id: 'admin_002',
    admin_nome: 'Escrivã Paula Nascimento',
    action: 'create',
    collection: 'sobreaviso',
    document_id: 'sobreaviso_003',
    timestamp: subDays(today, 1),
  },
  {
    id: 'audit_006',
    admin_id: 'admin_001',
    admin_nome: 'Delegado Marcos Vieira',
    action: 'update',
    collection: 'viagens',
    document_id: 'viagem_002',
    old_data: { status: 'pendente' },
    new_data: { status: 'confirmado' },
    timestamp: subDays(today, 2),
  },
  {
    id: 'audit_007',
    admin_id: 'admin_002',
    admin_nome: 'Escrivã Paula Nascimento',
    action: 'create',
    collection: 'impedimentos',
    document_id: 'impedimento_001',
    timestamp: subDays(today, 3),
  },
  {
    id: 'audit_008',
    admin_id: 'admin_001',
    admin_nome: 'Delegado Marcos Vieira',
    action: 'delete',
    collection: 'notificacoes',
    document_id: 'notif_old_001',
    timestamp: subDays(today, 4),
  },
];

export const MOCK_NOTIFICACOES: Notificacao[] = [
  {
    id: 'notif_001',
    policial_id: 'policial_demo_1',
    titulo: 'Nova Escala de Sobreaviso',
    mensagem: 'Você foi designado para sobreaviso em ' + today.toLocaleDateString('pt-BR') + '. Dê ciência.',
    tipo: 'sobreaviso',
    lida: false,
    created_at: subDays(today, 1),
  },
  {
    id: 'notif_002',
    policial_id: 'policial_demo_4',
    titulo: 'Missão de Viagem Registrada',
    mensagem: 'Viagem para Manaus - AM programada para os próximos dias. Confirme disponibilidade.',
    tipo: 'viagem',
    lida: false,
    created_at: subDays(today, 3),
  },
];
